[package]

name = "freetype-sys"
version = "0.23.0"
authors = ["Coeuvre <coeuvre@gmail.com>"]
links = "freetype"
build = "build.rs"
keywords = ["freetype", "ffi"]
description = "Low level binding for FreeType font library"
# This crate itself (the rust bindings) is MIT licensed,
# freetype2 is FTL or GPL-2.0 or later versions (at the users choice)
# and libpng is licensed under libpng-2.0
license = "MIT AND (FTL OR GPL-2.0-or-later) AND libpng-2.0"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/freetype-sys.git"
homepage = "https://github.com/PistonDevelopers/freetype-sys"
edition = "2018"

[features]
bundled = ["libz-sys"]

[dependencies]
libz-sys = {  version = "1.1.20", optional = true }

[build-dependencies]
cc = "1"
pkg-config = "0.3.11"
